"""extract_project.py
Place this in the root of dissertation_project/ and run:
    python extract_project.py

It generates project_snapshot.txt containing every code file's full content,
recursively across ALL directory layers (subdirectories are fully traversed).
"""
import os
from pathlib import Path

# === CONFIGURATION ===
OUTPUT_FILE = "project_snapshot.txt"
ROOT_DIR = Path(__file__).parent.resolve()

# Directory names whose contents should be skipped, but subdirs inside them
# are still traversed so we catch nested code at every layer.
SKIP_DIR_NAMES = {
    "__pycache__", ".git", ".idea", ".vscode", "venv", "env",
    "node_modules", ".pytest_cache", ".mypy_cache"
}

# File extensions to include
INCLUDE_EXTS = {".py", ".txt", ".md", ".yml", ".yaml", ".json", ".cfg", ".ini"}

# Specific filenames to include even without matching extension
INCLUDE_FILES = {"requirements", "README", "config", "main", "extract_project"}

# Maximum file size in bytes (skip files larger than this)
MAX_SIZE_BYTES = 2 * 1024 * 1024  # 2 MB


def should_include(file_path: Path) -> bool:
    """Decide whether to include a file in the snapshot."""
    # Skip hidden files
    if file_path.name.startswith("."):
        return False

    # Skip this script itself to avoid recursion
    if file_path.name == OUTPUT_FILE:
        return False

    # Skip files that live inside any known junk directory at ANY layer
    for part in file_path.parts:
        if part in SKIP_DIR_NAMES:
            return False

    # Skip by size
    try:
        if file_path.stat().st_size > MAX_SIZE_BYTES:
            return False
    except OSError:
        return False

    # Include by extension
    if file_path.suffix.lower() in INCLUDE_EXTS:
        return True

    # Include by name (for files without extension like 'requirements')
    if file_path.stem in INCLUDE_FILES:
        return True

    return False


def main():
    snapshot_lines = []
    snapshot_lines.append("=" * 80)
    snapshot_lines.append("PROJECT SNAPSHOT")
    snapshot_lines.append(f"Root: {ROOT_DIR}")
    snapshot_lines.append(f"Generated by: {Path(__file__).name}")
    snapshot_lines.append("=" * 80)
    snapshot_lines.append("")

    files_collected = 0

    # os.walk descends into EVERY subdirectory — no dirnames filtering
    for dirpath, _dirnames, filenames in os.walk(ROOT_DIR):
        current_dir = Path(dirpath)

        for filename in filenames:
            file_path = current_dir / filename

            if not should_include(file_path):
                continue

            try:
                content = file_path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                try:
                    content = file_path.read_text(encoding="latin-1")
                except Exception:
                    continue
            except Exception:
                continue

            relative_path = file_path.relative_to(ROOT_DIR)

            snapshot_lines.append("-" * 80)
            snapshot_lines.append(f"FILE: {relative_path}")
            snapshot_lines.append("-" * 80)
            snapshot_lines.append(content)
            # Ensure file ends with a newline before separator
            if content and not content.endswith("\n"):
                snapshot_lines.append("")
            snapshot_lines.append("")

            files_collected += 1

    snapshot_lines.append("=" * 80)
    snapshot_lines.append(f"END OF SNAPSHOT --- {files_collected} files collected")
    snapshot_lines.append("=" * 80)

    output_path = ROOT_DIR / OUTPUT_FILE
    output_path.write_text("\n".join(snapshot_lines), encoding="utf-8")

    print(f"Snapshot created: {output_path}")
    print(f"Files included: {files_collected}")
    print(f"Output size: {output_path.stat().st_size / 1024:.1f} KB")


if __name__ == "__main__":
    main()